---
site:
  url: https://docs.kubewarden.io
  title: Kubewarden
  start_page: 1.0@kubewarden:en:introduction.adoc

content:
  sources:
    - url: https://github.com/kubewarden/docs.git
      branches: [main]
      start_paths: [shared, docs/kw/version-*, docs/admission-controller/version-*, docs/sbom-scanner/v*]

ui:
  bundle:
    url: https://github.com/rancher/product-docs-ui/blob/main/build/ui-bundle.zip?raw=true
    snapshot: true
  supplemental_files: ./kw-community-docs-supp-files

asciidoc:
  attributes:
    kw-build-community: true
    ga-build: true
    page-pagination: ''
    tabs-sync-option: ''
  extensions:
    - '@asciidoctor/tabs'

antora:
  extensions:
    # - require: "@antora/pdf-extension"
    - require: "@antora/lunr-extension"
      index_latest_only: true
    - require: "@sntke/antora-mermaid-extension"
      script_stem: header-scripts
      mermaid_initialize_options:
    - require: ./product-docs-common/extensions/dynamic-loading-attributes/load-global-site-attributes.js
      attributefile: ./product-docs-common/global-attributes.yml
      enabled: true
    - require: ./product-docs-common/extensions/versions-latest-prerelease/vlp.js
      enabled: true


output:
  dir: build/site
