include::partial$variables.adoc[]

= Setup Development Environments
:revdate: 2026-09-22
:page-revdate: {revdate}

Runtime enforcer supports Tilt to run development environment in your local.

== Pre-requisite

* On a supported Linux host to run a local kubernetes cluster, install a one
  node kubernetes cluster.
* Setup golang development environments.

== Steps

. Clone the repository: `git clone
  https://github.com/kubewarden/runtime-enforcer.git`.
. Install https://kubernetes.io/docs/reference/kubectl/[kubectl] and
  https://helm.sh/[helm].
. Install https://docs.tilt.dev/install.html[tilt].
. Install https://github.com/libbpf/libbpf[libbpf], so you can build ebpf
  programs at your local.
. Create `tilt-settings.yaml` based on `tilt-settings.yaml.example`.
. Run `tilt up`. Related resources should be built and deployed.

You can use this command to list the policy proposals:

[source,sh]
----
kubectl get workloadpolicyproposals.runtimeenforcer.kubewarden.io -A
----

== Optional

=== golangci-lint

You may want to install a pre-commit hook for golangci-lint, so you can fix
linter issues at your local.

. Install golangci-lint, e.g., `go install
  github.com/golangci/golangci-lint/v2/cmd/golangci-lint@v2.6.0`
. Install pre-commit hooks. You can also use tools like
  https://typicode.github.io/husky/[husky] or
  https://pre-commit.com/[pre-commit].

[source,sh]
----
cat << EOF > .git/hooks/pre-commit
#!/bin/sh
golangci-lint-v2 run
EOF
chmod +x .git/hooks/pre-commit
----

If you are using https://pre-commit.com/[pre-commit], you can run the following
command to install the hooks we define in `.pre-commit-config.yaml`:

[source,sh]
----
pre-commit install --install-hooks --hook-type pre-commit --overwrite
# if you want to disable the hook
pre-commit uninstall --hook-type pre-commit
----

== Verified environment

* https://kind.sigs.k8s.io/[Kind] v1.32.2
* Ubuntu 22.04.5 LTS with 6.8.0-52-generic kernel.

== Run bpfvalidator on our ebpf instrumentation

Install bpfvalidator on your machine downloading it from
https://github.com/Andreagit97/bpfvalidator/releases, or build it from source.

From the root of the repo

[source,sh]
----
# generate a binary with bpf tests called `tester`
go test -c ./internal/bpf/... -o tester
# install bpfvalidator on you machine https://github.com/Andreagit97/bpfvalidator/releases
bpfvalidator --config ./bpfvalidator-amd64-config.yaml --cmd="./tester -test.v"
----
