= Typescript
:revdate: 2025-02-27
:page-revdate: {revdate}
:description: Writing Kubewarden policies with Typescript
:doc-persona: ["kubewarden-developer"]
:doc-topic: ["root-branch"]
:doc-type: ["tutorial"]
:keywords: ["kubewarden", "kubernetes", "typescript"]
:sidebar_label: Typescript
:sidebar_position: 60
:current-version: {page-origin-branch}

As stated on the https://www.typescriptlang.org/[official website]:

____
TypeScript extends JavaScript by adding types.

By understanding JavaScript, TypeScript saves you time catching errors and
providing fixes before you run code.
____

TypeScript can't target WebAssembly, however
https://www.assemblyscript.org/[AssemblyScript]
is a *subset* of TypeScript designed for WebAssembly.

== Current state

Currently, there's no Kubewarden SDK for AssemblyScript.
Resources permitting, we hope to have on in the near future.

However, there are limitations affecting AssemblyScript:

* There's no built-in way to serialize and deserialize Classes to
and from JSON.
See https://github.com/AssemblyScript/assemblyscript/issues/292[this issue]
* It _seems_ there's no JSON path library for AssemblyScript

== Example

https://github.com/kubewarden/pod-privileged-policy/tree/assemblyscript-implementation[This GitHub repository branch]
has a Kubewarden Policy written in AssemblyScript.

This repository has a series of GitHub Actions that automate the following tasks:

* Run unit tests and code linting on pull requests and after code is merged into the main branch
* Build the policy in `release` mode and push it to an OCI registry as an artifact
