include::partial$variables.adoc[]
= Glossary
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-03-18
:page-revdate: {revdate}
:description: Explore key resources and configurations related to {project-name} policies in Kubernetes environments for more information.
:doc-persona: ["kubewarden-all"]
:doc-topic: ["glossary"]
:doc-type: ["explanation"]
:keywords: ["kubewarden", "glossary"]
:sidebar_label: Glossary
:sidebar_position: 90
:current-version: {page-origin-branch}

== A

[#_admissionpolicy]
=== AdmissionPolicy

A namespace-wide resource. The policy processes only those requests targeting
the namespace in which the AdmissionPolicy is defined.

== C

[#_clusteradmissionpolicy]
=== ClusterAdmissionPolicy

An <<_admissionpolicy,AdmissionPolicy>> which targets cluster-wide resources.

[#_clusterreport]
=== ClusterReport

A <<_report,Report>> and a ClusterReport store results of policy scans. Which
one is used, depends on the scope of the resource.

== K

[#_kwctl]
=== kwctl

A CLI tool to generate and test Kubernetes YAML files for policy deployment.

== M

[#_mutatingwebhookconfiguration]
=== MutatingWebhookConfiguration

A
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks[Kubernetes resource]
created by the {short-project-name} controller to let Kubernetes know where to send an `AdmissionReview`.
In other words,
this is how a {short-project-name} controller informs Kubernetes where to find a resource mutating policy.

== R

[#_report]
=== Report

A Report and a <<_clusterreport,ClusterReport>> store results of
policy scans. Which one is used depends on the scope of the resource.

[#_policyserver]
=== PolicyServer

A PolicyServer validates incoming requests by executing {short-project-name} policies against requests.

== V

[#_validatingwebhookconfiguration]
=== ValidatingWebhookConfiguration

A
https://kubernetes.io/docs/reference/access-authn-authz/extensible-admission-controllers/#what-are-admission-webhooks[Kubernetes resource]
created by the {short-project-name} controller to let Kubernetes know where to send a `AdmissionReview`.
In other words, this is how {short-project-name} informs Kubernetes where to find a resource validating policy.

== W

[#_wapc]
=== waPC

WebAssembly Procedure Calls. https://wapc.io.

[#_wasi]
=== WASI

WebAssembly System Interface. https://wasi.dev.

[#_wasm]
=== Wasm

A binary instruction format for a stack-based virtual machine. Designed for web
deployment. https://webassembly.org.

[#_wasmtime]
=== Wasmtime

A runtime for WebAssembly. https://wasmtime.dev.
