= Policy settings
:revdate: 2024-09-10
:page-revdate: {revdate}
:description: Policy settings.
:doc-persona: ["kubewarden-policy-developer"]
:doc-topic: ["writing-policies", "specification", "settings"]
:doc-type: ["reference"]
:keywords: ["kubewarden", "kubernetes", "policy specification", "policy settings"]
:sidebar_label: Policy settings
:current-version: {page-origin-branch}

Policy behavior is not rigid,
it can be configured by providing configuration details to the policy at runtime.
The policy author has the freedom to define the structure of policy settings.

Kubewarden takes care of serializing the policy settings into JSON and provides them to the policy each time it is invoked.

== Settings validation

Policies should validate the settings a user provides to ensure correctness.

Each policy registers a waPC function called `validate_settings` that validates the policy settings.

The `validate_settings` function receives as input a JSON representation of the settings provided by the user.
This function validates them and returns as a response a `SettingsValidationResponse` object.

The structure of the `SettingsValidationResponse` object is:

[subs="+attributes",yaml]
----
{
  # mandatory
  "valid": <boolean>,

  # optional, ignored if accepted - recommended for rejections
  "message": <string>,
}
----

If the user provided settings are `valid`, the contents of `message` are ignored.
Otherwise, the contents of `message` are shown to the user.

[NOTE]
====
Kubewarden's
https://github.com/chimera-kube/policy-server[policy-server]
validates all the policy settings provided by users at start time.
The policy-server exits immediately with an error if at least one of its policies received wrong configuration parameters.
====


== Example

Let's take as an example the
https://github.com/kubewarden/psp-capabilities[psp-capabilities]
policy which has the following configuration format:

[subs="+attributes",yaml]
----
allowed_capabilities:
- CHOWN

required_drop_capabilities:
- NET_ADMIN

default_add_capabilities:
- KILL
----

The `validate_settings` function receives as input the following JSON
document:

[subs="+attributes",json]
----
{
  "allowed_capabilities": [
    "CHOWN"
  ],
  "required_drop_capabilities": [
    "NET_ADMIN"
  ],
  "default_add_capabilities": [
    "KILL"
  ]
}
----

== Recap

Each policy must register a waPC function, `validate_settings`.
