include::partial$variables.adoc[]

:title: {admc-name} artifacts
:description: Verify {admc-name} artifacts and access related binaries, Helm charts, for efficient security management.
:keywords: [artifacts, support, airgap, images]
:doc-persona: [kubewarden-operator]
:doc-type: [reference]
:doc-topic: [operator-manual, artifacts, registry, images]
:page-languages: [en, de, es, fr, ja, pt, zh]
:revdate: 2026-05-14
:page-revdate: {revdate}

= {title}

== Verifying {admc-name}

There is a tutorial on xref:/tutorials/verifying-kubewarden.adoc[verifying
{admc-short-name}] demonstrating how to verify {admc-short-name} artifacts.

== Binaries

{admc-name} publishes the `kwctl` CLI tool at
link:https://github.com/kubewarden/adm-controller/releases[GitHub releases].
Learn how to install it in the xref:/howtos/install-kwctl.adoc[install kwctl] documentation.

== OCI artifacts

For Open Container Initiative (OCI) artifacts, the project publishes everything
in `ghcr.io` under https://github.com/orgs/kubewarden/packages.

- https://github.com/orgs/kubewarden/packages/policies[`kubewarden/packages/policies/*`]
  are the policy Wasm OCI artifacts.
- https://github.com/orgs/kubewarden/packages/charts[`kubewarden/packages/charts/*`]
  are the Helm charts as OCI artifacts. They follow SLSA standards.
- the container images published as OCI images: `kubewarden-controller`, `policy-server`, `audit-scanner`, `kubectl`.
- there's also `packages/tests/*` containing artifacts used in e2e tests.

== Helm charts via HTTPS

{admc-short-name} publishes Helm charts in the Helm chart HTTPS repository at
https://charts.kubewarden.io. They're without SLSA, or signatures, but this
type of Helm repository provides searching.
