name: GitHub Pages

on:
  push:
    branches:
      - main
permissions:
  contents: read
  id-token: write
  pages: write

jobs:
  deploy:
    environment:
      name: github-pages
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main docs repo
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          submodules: true
          persist-credentials: false
      - name: Setup Antora
        uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
        with:
          node-version: 24.x
          cache: npm
      - name: Build website
        run: |
          make community-remote
      - name: Upload artifact for deployment
        uses: actions/upload-pages-artifact@fc324d3547104276b827a68afc52ff2a11cc49c9 # v5.0.0
        with:
          path: ./build/site
      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@368f82528645a54fb793d4d04e342629a3f51346 # v5.0.1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
