on: [pull_request]
name: Continuous integration

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout main docs repo
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          submodules: true
      - name: Setup Antora
        uses: actions/setup-node@cdca7365b2dadb8aad0a33bc7601856ffabcc48e # v4.4.4
        with:
          node-version: 22.x
          cache: npm
      - name: Build website
        run: |
          make community-remote
